import {
  LayoutDashboard,
  TrendingUp,
  Users,
  BarChart3,
  FileText,
  Send,
  Mail,
  Package,
  UserCog,
  Settings,
  Bell,
  ChevronDown,
  Menu,
  ChevronRight,
  ArrowLeft,
  Info,
  X,
  RefreshCw,
  MessageCircle,
  Clock,
  MapPin,
  Calendar,
  ShoppingCart,
  Edit3,
  Edit,
  AlertCircle,
  User,
  Phone,
  Lock,
  Eye,
  EyeOff,
  Construction,
  PlayCircle,
  CheckCircle,
  XCircle,
  Search,
  Filter,
  Plus,
  ChevronLeft,
  UserPlus,
  Activity,
  LogOut,
  AlertTriangle,
  Trophy,
  Archive,
  Scissors,
  MessageSquare,
  ShoppingBag,
  Star,
  Check,
  MailOpen,
  Save,
  Heart,
} from "lucide-vue-next";

export const iconComponents = {
  "layout-dashboard": LayoutDashboard,
  "trending-up": TrendingUp,
  users: Users,
  "bar-chart-3": BarChart3,
  "file-text": FileText,
  send: Send,
  mail: Mail,
  package: Package,
  "user-cog": UserCog,
  settings: Settings,
  bell: Bell,
  "chevron-down": ChevronDown,
  menu: Menu,
  "chevron-right": ChevronRight,
  "arrow-left": ArrowLeft,
  info: Info,
  x: X,
  "refresh-cw": RefreshCw,
  "message-circle": MessageCircle,
  clock: Clock,
  "map-pin": MapPin,
  calendar: Calendar,
  "shopping-cart": ShoppingCart,
  "edit-3": Edit3,
  edit: Edit,
  "alert-circle": AlertCircle,
  user: User,
  phone: Phone,
  lock: Lock,
  eye: Eye,
  "eye-off": EyeOff,
  construction: Construction,
  "play-circle": PlayCircle,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  search: Search,
  filter: Filter,
  plus: Plus,
  "chevron-left": ChevronLeft,
  "user-plus": UserPlus,
  activity: Activity,
  "log-out": LogOut,
  "alert-triangle": AlertTriangle,
  trophy: Trophy,
  archive: Archive,
  scissors: Scissors,
  "message-square": MessageSquare,
  "shopping-bag": ShoppingBag,
  star: Star,
  check: Check,
  "mail-open": MailOpen,
  save: Save,
  heart: Heart,
};

export type IconName = keyof typeof iconComponents;
